//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _02_ConsumingWebService.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://DotNet-areeba.com/webservice", ConfigurationName="ServiceReference.CalculatorWebServiceSoap")]
    public interface CalculatorWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name firstName from namespace http://DotNet-areeba.com/webservice is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://DotNet-areeba.com/webservice/PrintName", ReplyAction="*")]
        _02_ConsumingWebService.ServiceReference.PrintNameResponse PrintName(_02_ConsumingWebService.ServiceReference.PrintNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://DotNet-areeba.com/webservice/PrintName", ReplyAction="*")]
        System.Threading.Tasks.Task<_02_ConsumingWebService.ServiceReference.PrintNameResponse> PrintNameAsync(_02_ConsumingWebService.ServiceReference.PrintNameRequest request);
        
        // CODEGEN: Generating message contract since element name operation from namespace http://DotNet-areeba.com/webservice is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://DotNet-areeba.com/webservice/Calculator", ReplyAction="*")]
        _02_ConsumingWebService.ServiceReference.CalculatorResponse Calculator(_02_ConsumingWebService.ServiceReference.CalculatorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://DotNet-areeba.com/webservice/Calculator", ReplyAction="*")]
        System.Threading.Tasks.Task<_02_ConsumingWebService.ServiceReference.CalculatorResponse> CalculatorAsync(_02_ConsumingWebService.ServiceReference.CalculatorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://DotNet-areeba.com/webservice/Division", ReplyAction="*")]
        int Division(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://DotNet-areeba.com/webservice/Division", ReplyAction="*")]
        System.Threading.Tasks.Task<int> DivisionAsync(int a, int b);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PrintNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PrintName", Namespace="http://DotNet-areeba.com/webservice", Order=0)]
        public _02_ConsumingWebService.ServiceReference.PrintNameRequestBody Body;
        
        public PrintNameRequest() {
        }
        
        public PrintNameRequest(_02_ConsumingWebService.ServiceReference.PrintNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://DotNet-areeba.com/webservice")]
    public partial class PrintNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string firstName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string lastName;
        
        public PrintNameRequestBody() {
        }
        
        public PrintNameRequestBody(string firstName, string lastName) {
            this.firstName = firstName;
            this.lastName = lastName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PrintNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PrintNameResponse", Namespace="http://DotNet-areeba.com/webservice", Order=0)]
        public _02_ConsumingWebService.ServiceReference.PrintNameResponseBody Body;
        
        public PrintNameResponse() {
        }
        
        public PrintNameResponse(_02_ConsumingWebService.ServiceReference.PrintNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://DotNet-areeba.com/webservice")]
    public partial class PrintNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PrintNameResult;
        
        public PrintNameResponseBody() {
        }
        
        public PrintNameResponseBody(string PrintNameResult) {
            this.PrintNameResult = PrintNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalculatorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Calculator", Namespace="http://DotNet-areeba.com/webservice", Order=0)]
        public _02_ConsumingWebService.ServiceReference.CalculatorRequestBody Body;
        
        public CalculatorRequest() {
        }
        
        public CalculatorRequest(_02_ConsumingWebService.ServiceReference.CalculatorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://DotNet-areeba.com/webservice")]
    public partial class CalculatorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int firstValue;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int secondValue;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string operation;
        
        public CalculatorRequestBody() {
        }
        
        public CalculatorRequestBody(int firstValue, int secondValue, string operation) {
            this.firstValue = firstValue;
            this.secondValue = secondValue;
            this.operation = operation;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalculatorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalculatorResponse", Namespace="http://DotNet-areeba.com/webservice", Order=0)]
        public _02_ConsumingWebService.ServiceReference.CalculatorResponseBody Body;
        
        public CalculatorResponse() {
        }
        
        public CalculatorResponse(_02_ConsumingWebService.ServiceReference.CalculatorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://DotNet-areeba.com/webservice")]
    public partial class CalculatorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CalculatorResult;
        
        public CalculatorResponseBody() {
        }
        
        public CalculatorResponseBody(string CalculatorResult) {
            this.CalculatorResult = CalculatorResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CalculatorWebServiceSoapChannel : _02_ConsumingWebService.ServiceReference.CalculatorWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculatorWebServiceSoapClient : System.ServiceModel.ClientBase<_02_ConsumingWebService.ServiceReference.CalculatorWebServiceSoap>, _02_ConsumingWebService.ServiceReference.CalculatorWebServiceSoap {
        
        public CalculatorWebServiceSoapClient() {
        }
        
        public CalculatorWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculatorWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _02_ConsumingWebService.ServiceReference.PrintNameResponse _02_ConsumingWebService.ServiceReference.CalculatorWebServiceSoap.PrintName(_02_ConsumingWebService.ServiceReference.PrintNameRequest request) {
            return base.Channel.PrintName(request);
        }
        
        public string PrintName(string firstName, string lastName) {
            _02_ConsumingWebService.ServiceReference.PrintNameRequest inValue = new _02_ConsumingWebService.ServiceReference.PrintNameRequest();
            inValue.Body = new _02_ConsumingWebService.ServiceReference.PrintNameRequestBody();
            inValue.Body.firstName = firstName;
            inValue.Body.lastName = lastName;
            _02_ConsumingWebService.ServiceReference.PrintNameResponse retVal = ((_02_ConsumingWebService.ServiceReference.CalculatorWebServiceSoap)(this)).PrintName(inValue);
            return retVal.Body.PrintNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_02_ConsumingWebService.ServiceReference.PrintNameResponse> _02_ConsumingWebService.ServiceReference.CalculatorWebServiceSoap.PrintNameAsync(_02_ConsumingWebService.ServiceReference.PrintNameRequest request) {
            return base.Channel.PrintNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<_02_ConsumingWebService.ServiceReference.PrintNameResponse> PrintNameAsync(string firstName, string lastName) {
            _02_ConsumingWebService.ServiceReference.PrintNameRequest inValue = new _02_ConsumingWebService.ServiceReference.PrintNameRequest();
            inValue.Body = new _02_ConsumingWebService.ServiceReference.PrintNameRequestBody();
            inValue.Body.firstName = firstName;
            inValue.Body.lastName = lastName;
            return ((_02_ConsumingWebService.ServiceReference.CalculatorWebServiceSoap)(this)).PrintNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _02_ConsumingWebService.ServiceReference.CalculatorResponse _02_ConsumingWebService.ServiceReference.CalculatorWebServiceSoap.Calculator(_02_ConsumingWebService.ServiceReference.CalculatorRequest request) {
            return base.Channel.Calculator(request);
        }
        
        public string Calculator(int firstValue, int secondValue, string operation) {
            _02_ConsumingWebService.ServiceReference.CalculatorRequest inValue = new _02_ConsumingWebService.ServiceReference.CalculatorRequest();
            inValue.Body = new _02_ConsumingWebService.ServiceReference.CalculatorRequestBody();
            inValue.Body.firstValue = firstValue;
            inValue.Body.secondValue = secondValue;
            inValue.Body.operation = operation;
            _02_ConsumingWebService.ServiceReference.CalculatorResponse retVal = ((_02_ConsumingWebService.ServiceReference.CalculatorWebServiceSoap)(this)).Calculator(inValue);
            return retVal.Body.CalculatorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_02_ConsumingWebService.ServiceReference.CalculatorResponse> _02_ConsumingWebService.ServiceReference.CalculatorWebServiceSoap.CalculatorAsync(_02_ConsumingWebService.ServiceReference.CalculatorRequest request) {
            return base.Channel.CalculatorAsync(request);
        }
        
        public System.Threading.Tasks.Task<_02_ConsumingWebService.ServiceReference.CalculatorResponse> CalculatorAsync(int firstValue, int secondValue, string operation) {
            _02_ConsumingWebService.ServiceReference.CalculatorRequest inValue = new _02_ConsumingWebService.ServiceReference.CalculatorRequest();
            inValue.Body = new _02_ConsumingWebService.ServiceReference.CalculatorRequestBody();
            inValue.Body.firstValue = firstValue;
            inValue.Body.secondValue = secondValue;
            inValue.Body.operation = operation;
            return ((_02_ConsumingWebService.ServiceReference.CalculatorWebServiceSoap)(this)).CalculatorAsync(inValue);
        }
        
        public int Division(int a, int b) {
            return base.Channel.Division(a, b);
        }
        
        public System.Threading.Tasks.Task<int> DivisionAsync(int a, int b) {
            return base.Channel.DivisionAsync(a, b);
        }
    }
}
