//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _02_ConsumingWebService.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebServiceResponse", Namespace="http://DotNet-areeba.com/webservice")]
    [System.SerializableAttribute()]
    public partial class WebServiceResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://DotNet-areeba.com/webservice", ConfigurationName="ServiceReference.CalculatorWebServiceSoap")]
    public interface CalculatorWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name firstName from namespace http://DotNet-areeba.com/webservice is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://DotNet-areeba.com/webservice/PrintName", ReplyAction="*")]
        _02_ConsumingWebService.ServiceReference.PrintNameResponse PrintName(_02_ConsumingWebService.ServiceReference.PrintNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://DotNet-areeba.com/webservice/PrintName", ReplyAction="*")]
        System.Threading.Tasks.Task<_02_ConsumingWebService.ServiceReference.PrintNameResponse> PrintNameAsync(_02_ConsumingWebService.ServiceReference.PrintNameRequest request);
        
        // CODEGEN: Generating message contract since element name operation from namespace http://DotNet-areeba.com/webservice is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://DotNet-areeba.com/webservice/Calculator", ReplyAction="*")]
        _02_ConsumingWebService.ServiceReference.CalculatorResponse Calculator(_02_ConsumingWebService.ServiceReference.CalculatorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://DotNet-areeba.com/webservice/Calculator", ReplyAction="*")]
        System.Threading.Tasks.Task<_02_ConsumingWebService.ServiceReference.CalculatorResponse> CalculatorAsync(_02_ConsumingWebService.ServiceReference.CalculatorRequest request);
        
        // CODEGEN: Generating message contract since element name DivisionResult from namespace http://DotNet-areeba.com/webservice is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://DotNet-areeba.com/webservice/Division", ReplyAction="*")]
        _02_ConsumingWebService.ServiceReference.DivisionResponse Division(_02_ConsumingWebService.ServiceReference.DivisionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://DotNet-areeba.com/webservice/Division", ReplyAction="*")]
        System.Threading.Tasks.Task<_02_ConsumingWebService.ServiceReference.DivisionResponse> DivisionAsync(_02_ConsumingWebService.ServiceReference.DivisionRequest request);
        
        // CODEGEN: Generating message contract since element name AdditionResult from namespace http://DotNet-areeba.com/webservice is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://DotNet-areeba.com/webservice/Addition", ReplyAction="*")]
        _02_ConsumingWebService.ServiceReference.AdditionResponse Addition(_02_ConsumingWebService.ServiceReference.AdditionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://DotNet-areeba.com/webservice/Addition", ReplyAction="*")]
        System.Threading.Tasks.Task<_02_ConsumingWebService.ServiceReference.AdditionResponse> AdditionAsync(_02_ConsumingWebService.ServiceReference.AdditionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PrintNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PrintName", Namespace="http://DotNet-areeba.com/webservice", Order=0)]
        public _02_ConsumingWebService.ServiceReference.PrintNameRequestBody Body;
        
        public PrintNameRequest() {
        }
        
        public PrintNameRequest(_02_ConsumingWebService.ServiceReference.PrintNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://DotNet-areeba.com/webservice")]
    public partial class PrintNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string firstName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string lastName;
        
        public PrintNameRequestBody() {
        }
        
        public PrintNameRequestBody(string firstName, string lastName) {
            this.firstName = firstName;
            this.lastName = lastName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PrintNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PrintNameResponse", Namespace="http://DotNet-areeba.com/webservice", Order=0)]
        public _02_ConsumingWebService.ServiceReference.PrintNameResponseBody Body;
        
        public PrintNameResponse() {
        }
        
        public PrintNameResponse(_02_ConsumingWebService.ServiceReference.PrintNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://DotNet-areeba.com/webservice")]
    public partial class PrintNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PrintNameResult;
        
        public PrintNameResponseBody() {
        }
        
        public PrintNameResponseBody(string PrintNameResult) {
            this.PrintNameResult = PrintNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalculatorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Calculator", Namespace="http://DotNet-areeba.com/webservice", Order=0)]
        public _02_ConsumingWebService.ServiceReference.CalculatorRequestBody Body;
        
        public CalculatorRequest() {
        }
        
        public CalculatorRequest(_02_ConsumingWebService.ServiceReference.CalculatorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://DotNet-areeba.com/webservice")]
    public partial class CalculatorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int firstValue;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int secondValue;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string operation;
        
        public CalculatorRequestBody() {
        }
        
        public CalculatorRequestBody(int firstValue, int secondValue, string operation) {
            this.firstValue = firstValue;
            this.secondValue = secondValue;
            this.operation = operation;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalculatorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalculatorResponse", Namespace="http://DotNet-areeba.com/webservice", Order=0)]
        public _02_ConsumingWebService.ServiceReference.CalculatorResponseBody Body;
        
        public CalculatorResponse() {
        }
        
        public CalculatorResponse(_02_ConsumingWebService.ServiceReference.CalculatorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://DotNet-areeba.com/webservice")]
    public partial class CalculatorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CalculatorResult;
        
        public CalculatorResponseBody() {
        }
        
        public CalculatorResponseBody(string CalculatorResult) {
            this.CalculatorResult = CalculatorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DivisionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Division", Namespace="http://DotNet-areeba.com/webservice", Order=0)]
        public _02_ConsumingWebService.ServiceReference.DivisionRequestBody Body;
        
        public DivisionRequest() {
        }
        
        public DivisionRequest(_02_ConsumingWebService.ServiceReference.DivisionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://DotNet-areeba.com/webservice")]
    public partial class DivisionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int a;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int b;
        
        public DivisionRequestBody() {
        }
        
        public DivisionRequestBody(int a, int b) {
            this.a = a;
            this.b = b;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DivisionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DivisionResponse", Namespace="http://DotNet-areeba.com/webservice", Order=0)]
        public _02_ConsumingWebService.ServiceReference.DivisionResponseBody Body;
        
        public DivisionResponse() {
        }
        
        public DivisionResponse(_02_ConsumingWebService.ServiceReference.DivisionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://DotNet-areeba.com/webservice")]
    public partial class DivisionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public _02_ConsumingWebService.ServiceReference.WebServiceResponse DivisionResult;
        
        public DivisionResponseBody() {
        }
        
        public DivisionResponseBody(_02_ConsumingWebService.ServiceReference.WebServiceResponse DivisionResult) {
            this.DivisionResult = DivisionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AdditionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Addition", Namespace="http://DotNet-areeba.com/webservice", Order=0)]
        public _02_ConsumingWebService.ServiceReference.AdditionRequestBody Body;
        
        public AdditionRequest() {
        }
        
        public AdditionRequest(_02_ConsumingWebService.ServiceReference.AdditionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://DotNet-areeba.com/webservice")]
    public partial class AdditionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int a;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int b;
        
        public AdditionRequestBody() {
        }
        
        public AdditionRequestBody(int a, int b) {
            this.a = a;
            this.b = b;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AdditionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AdditionResponse", Namespace="http://DotNet-areeba.com/webservice", Order=0)]
        public _02_ConsumingWebService.ServiceReference.AdditionResponseBody Body;
        
        public AdditionResponse() {
        }
        
        public AdditionResponse(_02_ConsumingWebService.ServiceReference.AdditionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://DotNet-areeba.com/webservice")]
    public partial class AdditionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AdditionResult;
        
        public AdditionResponseBody() {
        }
        
        public AdditionResponseBody(string AdditionResult) {
            this.AdditionResult = AdditionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CalculatorWebServiceSoapChannel : _02_ConsumingWebService.ServiceReference.CalculatorWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculatorWebServiceSoapClient : System.ServiceModel.ClientBase<_02_ConsumingWebService.ServiceReference.CalculatorWebServiceSoap>, _02_ConsumingWebService.ServiceReference.CalculatorWebServiceSoap {
        
        public CalculatorWebServiceSoapClient() {
        }
        
        public CalculatorWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculatorWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _02_ConsumingWebService.ServiceReference.PrintNameResponse _02_ConsumingWebService.ServiceReference.CalculatorWebServiceSoap.PrintName(_02_ConsumingWebService.ServiceReference.PrintNameRequest request) {
            return base.Channel.PrintName(request);
        }
        
        public string PrintName(string firstName, string lastName) {
            _02_ConsumingWebService.ServiceReference.PrintNameRequest inValue = new _02_ConsumingWebService.ServiceReference.PrintNameRequest();
            inValue.Body = new _02_ConsumingWebService.ServiceReference.PrintNameRequestBody();
            inValue.Body.firstName = firstName;
            inValue.Body.lastName = lastName;
            _02_ConsumingWebService.ServiceReference.PrintNameResponse retVal = ((_02_ConsumingWebService.ServiceReference.CalculatorWebServiceSoap)(this)).PrintName(inValue);
            return retVal.Body.PrintNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_02_ConsumingWebService.ServiceReference.PrintNameResponse> _02_ConsumingWebService.ServiceReference.CalculatorWebServiceSoap.PrintNameAsync(_02_ConsumingWebService.ServiceReference.PrintNameRequest request) {
            return base.Channel.PrintNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<_02_ConsumingWebService.ServiceReference.PrintNameResponse> PrintNameAsync(string firstName, string lastName) {
            _02_ConsumingWebService.ServiceReference.PrintNameRequest inValue = new _02_ConsumingWebService.ServiceReference.PrintNameRequest();
            inValue.Body = new _02_ConsumingWebService.ServiceReference.PrintNameRequestBody();
            inValue.Body.firstName = firstName;
            inValue.Body.lastName = lastName;
            return ((_02_ConsumingWebService.ServiceReference.CalculatorWebServiceSoap)(this)).PrintNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _02_ConsumingWebService.ServiceReference.CalculatorResponse _02_ConsumingWebService.ServiceReference.CalculatorWebServiceSoap.Calculator(_02_ConsumingWebService.ServiceReference.CalculatorRequest request) {
            return base.Channel.Calculator(request);
        }
        
        public string Calculator(int firstValue, int secondValue, string operation) {
            _02_ConsumingWebService.ServiceReference.CalculatorRequest inValue = new _02_ConsumingWebService.ServiceReference.CalculatorRequest();
            inValue.Body = new _02_ConsumingWebService.ServiceReference.CalculatorRequestBody();
            inValue.Body.firstValue = firstValue;
            inValue.Body.secondValue = secondValue;
            inValue.Body.operation = operation;
            _02_ConsumingWebService.ServiceReference.CalculatorResponse retVal = ((_02_ConsumingWebService.ServiceReference.CalculatorWebServiceSoap)(this)).Calculator(inValue);
            return retVal.Body.CalculatorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_02_ConsumingWebService.ServiceReference.CalculatorResponse> _02_ConsumingWebService.ServiceReference.CalculatorWebServiceSoap.CalculatorAsync(_02_ConsumingWebService.ServiceReference.CalculatorRequest request) {
            return base.Channel.CalculatorAsync(request);
        }
        
        public System.Threading.Tasks.Task<_02_ConsumingWebService.ServiceReference.CalculatorResponse> CalculatorAsync(int firstValue, int secondValue, string operation) {
            _02_ConsumingWebService.ServiceReference.CalculatorRequest inValue = new _02_ConsumingWebService.ServiceReference.CalculatorRequest();
            inValue.Body = new _02_ConsumingWebService.ServiceReference.CalculatorRequestBody();
            inValue.Body.firstValue = firstValue;
            inValue.Body.secondValue = secondValue;
            inValue.Body.operation = operation;
            return ((_02_ConsumingWebService.ServiceReference.CalculatorWebServiceSoap)(this)).CalculatorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _02_ConsumingWebService.ServiceReference.DivisionResponse _02_ConsumingWebService.ServiceReference.CalculatorWebServiceSoap.Division(_02_ConsumingWebService.ServiceReference.DivisionRequest request) {
            return base.Channel.Division(request);
        }
        
        public _02_ConsumingWebService.ServiceReference.WebServiceResponse Division(int a, int b) {
            _02_ConsumingWebService.ServiceReference.DivisionRequest inValue = new _02_ConsumingWebService.ServiceReference.DivisionRequest();
            inValue.Body = new _02_ConsumingWebService.ServiceReference.DivisionRequestBody();
            inValue.Body.a = a;
            inValue.Body.b = b;
            _02_ConsumingWebService.ServiceReference.DivisionResponse retVal = ((_02_ConsumingWebService.ServiceReference.CalculatorWebServiceSoap)(this)).Division(inValue);
            return retVal.Body.DivisionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_02_ConsumingWebService.ServiceReference.DivisionResponse> _02_ConsumingWebService.ServiceReference.CalculatorWebServiceSoap.DivisionAsync(_02_ConsumingWebService.ServiceReference.DivisionRequest request) {
            return base.Channel.DivisionAsync(request);
        }
        
        public System.Threading.Tasks.Task<_02_ConsumingWebService.ServiceReference.DivisionResponse> DivisionAsync(int a, int b) {
            _02_ConsumingWebService.ServiceReference.DivisionRequest inValue = new _02_ConsumingWebService.ServiceReference.DivisionRequest();
            inValue.Body = new _02_ConsumingWebService.ServiceReference.DivisionRequestBody();
            inValue.Body.a = a;
            inValue.Body.b = b;
            return ((_02_ConsumingWebService.ServiceReference.CalculatorWebServiceSoap)(this)).DivisionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _02_ConsumingWebService.ServiceReference.AdditionResponse _02_ConsumingWebService.ServiceReference.CalculatorWebServiceSoap.Addition(_02_ConsumingWebService.ServiceReference.AdditionRequest request) {
            return base.Channel.Addition(request);
        }
        
        public string Addition(int a, int b) {
            _02_ConsumingWebService.ServiceReference.AdditionRequest inValue = new _02_ConsumingWebService.ServiceReference.AdditionRequest();
            inValue.Body = new _02_ConsumingWebService.ServiceReference.AdditionRequestBody();
            inValue.Body.a = a;
            inValue.Body.b = b;
            _02_ConsumingWebService.ServiceReference.AdditionResponse retVal = ((_02_ConsumingWebService.ServiceReference.CalculatorWebServiceSoap)(this)).Addition(inValue);
            return retVal.Body.AdditionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_02_ConsumingWebService.ServiceReference.AdditionResponse> _02_ConsumingWebService.ServiceReference.CalculatorWebServiceSoap.AdditionAsync(_02_ConsumingWebService.ServiceReference.AdditionRequest request) {
            return base.Channel.AdditionAsync(request);
        }
        
        public System.Threading.Tasks.Task<_02_ConsumingWebService.ServiceReference.AdditionResponse> AdditionAsync(int a, int b) {
            _02_ConsumingWebService.ServiceReference.AdditionRequest inValue = new _02_ConsumingWebService.ServiceReference.AdditionRequest();
            inValue.Body = new _02_ConsumingWebService.ServiceReference.AdditionRequestBody();
            inValue.Body.a = a;
            inValue.Body.b = b;
            return ((_02_ConsumingWebService.ServiceReference.CalculatorWebServiceSoap)(this)).AdditionAsync(inValue);
        }
    }
}
