//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _03_ClientSessionWebService.SessionsWebServiceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://DotNet-areeba.com/sessionswebservice", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://DotNet-areeba.com/sessionswebservice", ConfigurationName="SessionsWebServiceRef.SessionsWebServiceSoap")]
    public interface SessionsWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name name from namespace http://DotNet-areeba.com/sessionswebservice is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://DotNet-areeba.com/sessionswebservice/PrintName", ReplyAction="*")]
        _03_ClientSessionWebService.SessionsWebServiceRef.PrintNameResponse PrintName(_03_ClientSessionWebService.SessionsWebServiceRef.PrintNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://DotNet-areeba.com/sessionswebservice/PrintName", ReplyAction="*")]
        System.Threading.Tasks.Task<_03_ClientSessionWebService.SessionsWebServiceRef.PrintNameResponse> PrintNameAsync(_03_ClientSessionWebService.SessionsWebServiceRef.PrintNameRequest request);
        
        // CODEGEN: Generating message contract since element name GetNamesResult from namespace http://DotNet-areeba.com/sessionswebservice is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://DotNet-areeba.com/sessionswebservice/GetNames", ReplyAction="*")]
        _03_ClientSessionWebService.SessionsWebServiceRef.GetNamesResponse GetNames(_03_ClientSessionWebService.SessionsWebServiceRef.GetNamesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://DotNet-areeba.com/sessionswebservice/GetNames", ReplyAction="*")]
        System.Threading.Tasks.Task<_03_ClientSessionWebService.SessionsWebServiceRef.GetNamesResponse> GetNamesAsync(_03_ClientSessionWebService.SessionsWebServiceRef.GetNamesRequest request);
        
        // CODEGEN: Generating message contract since element name GetCountResult from namespace http://DotNet-areeba.com/sessionswebservice is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://DotNet-areeba.com/sessionswebservice/GetCount", ReplyAction="*")]
        _03_ClientSessionWebService.SessionsWebServiceRef.GetCountResponse GetCount(_03_ClientSessionWebService.SessionsWebServiceRef.GetCountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://DotNet-areeba.com/sessionswebservice/GetCount", ReplyAction="*")]
        System.Threading.Tasks.Task<_03_ClientSessionWebService.SessionsWebServiceRef.GetCountResponse> GetCountAsync(_03_ClientSessionWebService.SessionsWebServiceRef.GetCountRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PrintNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PrintName", Namespace="http://DotNet-areeba.com/sessionswebservice", Order=0)]
        public _03_ClientSessionWebService.SessionsWebServiceRef.PrintNameRequestBody Body;
        
        public PrintNameRequest() {
        }
        
        public PrintNameRequest(_03_ClientSessionWebService.SessionsWebServiceRef.PrintNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://DotNet-areeba.com/sessionswebservice")]
    public partial class PrintNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public PrintNameRequestBody() {
        }
        
        public PrintNameRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PrintNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PrintNameResponse", Namespace="http://DotNet-areeba.com/sessionswebservice", Order=0)]
        public _03_ClientSessionWebService.SessionsWebServiceRef.PrintNameResponseBody Body;
        
        public PrintNameResponse() {
        }
        
        public PrintNameResponse(_03_ClientSessionWebService.SessionsWebServiceRef.PrintNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://DotNet-areeba.com/sessionswebservice")]
    public partial class PrintNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PrintNameResult;
        
        public PrintNameResponseBody() {
        }
        
        public PrintNameResponseBody(string PrintNameResult) {
            this.PrintNameResult = PrintNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNamesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNames", Namespace="http://DotNet-areeba.com/sessionswebservice", Order=0)]
        public _03_ClientSessionWebService.SessionsWebServiceRef.GetNamesRequestBody Body;
        
        public GetNamesRequest() {
        }
        
        public GetNamesRequest(_03_ClientSessionWebService.SessionsWebServiceRef.GetNamesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetNamesRequestBody {
        
        public GetNamesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNamesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNamesResponse", Namespace="http://DotNet-areeba.com/sessionswebservice", Order=0)]
        public _03_ClientSessionWebService.SessionsWebServiceRef.GetNamesResponseBody Body;
        
        public GetNamesResponse() {
        }
        
        public GetNamesResponse(_03_ClientSessionWebService.SessionsWebServiceRef.GetNamesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://DotNet-areeba.com/sessionswebservice")]
    public partial class GetNamesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public _03_ClientSessionWebService.SessionsWebServiceRef.ArrayOfString GetNamesResult;
        
        public GetNamesResponseBody() {
        }
        
        public GetNamesResponseBody(_03_ClientSessionWebService.SessionsWebServiceRef.ArrayOfString GetNamesResult) {
            this.GetNamesResult = GetNamesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCount", Namespace="http://DotNet-areeba.com/sessionswebservice", Order=0)]
        public _03_ClientSessionWebService.SessionsWebServiceRef.GetCountRequestBody Body;
        
        public GetCountRequest() {
        }
        
        public GetCountRequest(_03_ClientSessionWebService.SessionsWebServiceRef.GetCountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetCountRequestBody {
        
        public GetCountRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCountResponse", Namespace="http://DotNet-areeba.com/sessionswebservice", Order=0)]
        public _03_ClientSessionWebService.SessionsWebServiceRef.GetCountResponseBody Body;
        
        public GetCountResponse() {
        }
        
        public GetCountResponse(_03_ClientSessionWebService.SessionsWebServiceRef.GetCountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://DotNet-areeba.com/sessionswebservice")]
    public partial class GetCountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetCountResult;
        
        public GetCountResponseBody() {
        }
        
        public GetCountResponseBody(string GetCountResult) {
            this.GetCountResult = GetCountResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SessionsWebServiceSoapChannel : _03_ClientSessionWebService.SessionsWebServiceRef.SessionsWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SessionsWebServiceSoapClient : System.ServiceModel.ClientBase<_03_ClientSessionWebService.SessionsWebServiceRef.SessionsWebServiceSoap>, _03_ClientSessionWebService.SessionsWebServiceRef.SessionsWebServiceSoap {
        
        public SessionsWebServiceSoapClient() {
        }
        
        public SessionsWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SessionsWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SessionsWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SessionsWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _03_ClientSessionWebService.SessionsWebServiceRef.PrintNameResponse _03_ClientSessionWebService.SessionsWebServiceRef.SessionsWebServiceSoap.PrintName(_03_ClientSessionWebService.SessionsWebServiceRef.PrintNameRequest request) {
            return base.Channel.PrintName(request);
        }
        
        public string PrintName(string name) {
            _03_ClientSessionWebService.SessionsWebServiceRef.PrintNameRequest inValue = new _03_ClientSessionWebService.SessionsWebServiceRef.PrintNameRequest();
            inValue.Body = new _03_ClientSessionWebService.SessionsWebServiceRef.PrintNameRequestBody();
            inValue.Body.name = name;
            _03_ClientSessionWebService.SessionsWebServiceRef.PrintNameResponse retVal = ((_03_ClientSessionWebService.SessionsWebServiceRef.SessionsWebServiceSoap)(this)).PrintName(inValue);
            return retVal.Body.PrintNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_03_ClientSessionWebService.SessionsWebServiceRef.PrintNameResponse> _03_ClientSessionWebService.SessionsWebServiceRef.SessionsWebServiceSoap.PrintNameAsync(_03_ClientSessionWebService.SessionsWebServiceRef.PrintNameRequest request) {
            return base.Channel.PrintNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<_03_ClientSessionWebService.SessionsWebServiceRef.PrintNameResponse> PrintNameAsync(string name) {
            _03_ClientSessionWebService.SessionsWebServiceRef.PrintNameRequest inValue = new _03_ClientSessionWebService.SessionsWebServiceRef.PrintNameRequest();
            inValue.Body = new _03_ClientSessionWebService.SessionsWebServiceRef.PrintNameRequestBody();
            inValue.Body.name = name;
            return ((_03_ClientSessionWebService.SessionsWebServiceRef.SessionsWebServiceSoap)(this)).PrintNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _03_ClientSessionWebService.SessionsWebServiceRef.GetNamesResponse _03_ClientSessionWebService.SessionsWebServiceRef.SessionsWebServiceSoap.GetNames(_03_ClientSessionWebService.SessionsWebServiceRef.GetNamesRequest request) {
            return base.Channel.GetNames(request);
        }
        
        public _03_ClientSessionWebService.SessionsWebServiceRef.ArrayOfString GetNames() {
            _03_ClientSessionWebService.SessionsWebServiceRef.GetNamesRequest inValue = new _03_ClientSessionWebService.SessionsWebServiceRef.GetNamesRequest();
            inValue.Body = new _03_ClientSessionWebService.SessionsWebServiceRef.GetNamesRequestBody();
            _03_ClientSessionWebService.SessionsWebServiceRef.GetNamesResponse retVal = ((_03_ClientSessionWebService.SessionsWebServiceRef.SessionsWebServiceSoap)(this)).GetNames(inValue);
            return retVal.Body.GetNamesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_03_ClientSessionWebService.SessionsWebServiceRef.GetNamesResponse> _03_ClientSessionWebService.SessionsWebServiceRef.SessionsWebServiceSoap.GetNamesAsync(_03_ClientSessionWebService.SessionsWebServiceRef.GetNamesRequest request) {
            return base.Channel.GetNamesAsync(request);
        }
        
        public System.Threading.Tasks.Task<_03_ClientSessionWebService.SessionsWebServiceRef.GetNamesResponse> GetNamesAsync() {
            _03_ClientSessionWebService.SessionsWebServiceRef.GetNamesRequest inValue = new _03_ClientSessionWebService.SessionsWebServiceRef.GetNamesRequest();
            inValue.Body = new _03_ClientSessionWebService.SessionsWebServiceRef.GetNamesRequestBody();
            return ((_03_ClientSessionWebService.SessionsWebServiceRef.SessionsWebServiceSoap)(this)).GetNamesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _03_ClientSessionWebService.SessionsWebServiceRef.GetCountResponse _03_ClientSessionWebService.SessionsWebServiceRef.SessionsWebServiceSoap.GetCount(_03_ClientSessionWebService.SessionsWebServiceRef.GetCountRequest request) {
            return base.Channel.GetCount(request);
        }
        
        public string GetCount() {
            _03_ClientSessionWebService.SessionsWebServiceRef.GetCountRequest inValue = new _03_ClientSessionWebService.SessionsWebServiceRef.GetCountRequest();
            inValue.Body = new _03_ClientSessionWebService.SessionsWebServiceRef.GetCountRequestBody();
            _03_ClientSessionWebService.SessionsWebServiceRef.GetCountResponse retVal = ((_03_ClientSessionWebService.SessionsWebServiceRef.SessionsWebServiceSoap)(this)).GetCount(inValue);
            return retVal.Body.GetCountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_03_ClientSessionWebService.SessionsWebServiceRef.GetCountResponse> _03_ClientSessionWebService.SessionsWebServiceRef.SessionsWebServiceSoap.GetCountAsync(_03_ClientSessionWebService.SessionsWebServiceRef.GetCountRequest request) {
            return base.Channel.GetCountAsync(request);
        }
        
        public System.Threading.Tasks.Task<_03_ClientSessionWebService.SessionsWebServiceRef.GetCountResponse> GetCountAsync() {
            _03_ClientSessionWebService.SessionsWebServiceRef.GetCountRequest inValue = new _03_ClientSessionWebService.SessionsWebServiceRef.GetCountRequest();
            inValue.Body = new _03_ClientSessionWebService.SessionsWebServiceRef.GetCountRequestBody();
            return ((_03_ClientSessionWebService.SessionsWebServiceRef.SessionsWebServiceSoap)(this)).GetCountAsync(inValue);
        }
    }
}
