//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _04_ClientTimeOutWebService.TimeOutWebServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://DotNet-areeba.com/timeoutwebservice", ConfigurationName="TimeOutWebServiceRef.TimeOutWebServiceSoap")]
    public interface TimeOutWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name GreetUserResult from namespace http://DotNet-areeba.com/timeoutwebservice is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://DotNet-areeba.com/timeoutwebservice/GreetUser", ReplyAction="*")]
        _04_ClientTimeOutWebService.TimeOutWebServiceRef.GreetUserResponse GreetUser(_04_ClientTimeOutWebService.TimeOutWebServiceRef.GreetUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://DotNet-areeba.com/timeoutwebservice/GreetUser", ReplyAction="*")]
        System.Threading.Tasks.Task<_04_ClientTimeOutWebService.TimeOutWebServiceRef.GreetUserResponse> GreetUserAsync(_04_ClientTimeOutWebService.TimeOutWebServiceRef.GreetUserRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GreetUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GreetUser", Namespace="http://DotNet-areeba.com/timeoutwebservice", Order=0)]
        public _04_ClientTimeOutWebService.TimeOutWebServiceRef.GreetUserRequestBody Body;
        
        public GreetUserRequest() {
        }
        
        public GreetUserRequest(_04_ClientTimeOutWebService.TimeOutWebServiceRef.GreetUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GreetUserRequestBody {
        
        public GreetUserRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GreetUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GreetUserResponse", Namespace="http://DotNet-areeba.com/timeoutwebservice", Order=0)]
        public _04_ClientTimeOutWebService.TimeOutWebServiceRef.GreetUserResponseBody Body;
        
        public GreetUserResponse() {
        }
        
        public GreetUserResponse(_04_ClientTimeOutWebService.TimeOutWebServiceRef.GreetUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://DotNet-areeba.com/timeoutwebservice")]
    public partial class GreetUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GreetUserResult;
        
        public GreetUserResponseBody() {
        }
        
        public GreetUserResponseBody(string GreetUserResult) {
            this.GreetUserResult = GreetUserResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TimeOutWebServiceSoapChannel : _04_ClientTimeOutWebService.TimeOutWebServiceRef.TimeOutWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TimeOutWebServiceSoapClient : System.ServiceModel.ClientBase<_04_ClientTimeOutWebService.TimeOutWebServiceRef.TimeOutWebServiceSoap>, _04_ClientTimeOutWebService.TimeOutWebServiceRef.TimeOutWebServiceSoap {
        
        public TimeOutWebServiceSoapClient() {
        }
        
        public TimeOutWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TimeOutWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TimeOutWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TimeOutWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _04_ClientTimeOutWebService.TimeOutWebServiceRef.GreetUserResponse _04_ClientTimeOutWebService.TimeOutWebServiceRef.TimeOutWebServiceSoap.GreetUser(_04_ClientTimeOutWebService.TimeOutWebServiceRef.GreetUserRequest request) {
            return base.Channel.GreetUser(request);
        }
        
        public string GreetUser() {
            _04_ClientTimeOutWebService.TimeOutWebServiceRef.GreetUserRequest inValue = new _04_ClientTimeOutWebService.TimeOutWebServiceRef.GreetUserRequest();
            inValue.Body = new _04_ClientTimeOutWebService.TimeOutWebServiceRef.GreetUserRequestBody();
            _04_ClientTimeOutWebService.TimeOutWebServiceRef.GreetUserResponse retVal = ((_04_ClientTimeOutWebService.TimeOutWebServiceRef.TimeOutWebServiceSoap)(this)).GreetUser(inValue);
            return retVal.Body.GreetUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_04_ClientTimeOutWebService.TimeOutWebServiceRef.GreetUserResponse> _04_ClientTimeOutWebService.TimeOutWebServiceRef.TimeOutWebServiceSoap.GreetUserAsync(_04_ClientTimeOutWebService.TimeOutWebServiceRef.GreetUserRequest request) {
            return base.Channel.GreetUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<_04_ClientTimeOutWebService.TimeOutWebServiceRef.GreetUserResponse> GreetUserAsync() {
            _04_ClientTimeOutWebService.TimeOutWebServiceRef.GreetUserRequest inValue = new _04_ClientTimeOutWebService.TimeOutWebServiceRef.GreetUserRequest();
            inValue.Body = new _04_ClientTimeOutWebService.TimeOutWebServiceRef.GreetUserRequestBody();
            return ((_04_ClientTimeOutWebService.TimeOutWebServiceRef.TimeOutWebServiceSoap)(this)).GreetUserAsync(inValue);
        }
    }
}
